### ISSUE TITLE
Add Project License

### ISSUE THREAD

**Issue by zschuessler** [csalmeida/hozokit#13]
Hi, cool project!

I'd like to contribute, but the project needs a license file first.

Do you have a license in mind for this project? 
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

Thanks!

**Comment by csalmeida** [comment]
Hi Zachary!

Thanks for your interest, your contributions would be welcomed!

As for the license, Hozokit is derivative from Wordpress and inherits the [GNU General Public License version 2](https://opensource.org/licenses/gpl-2.0.php), projects made with Hozokit also have to use a GPL license, version 2 or later.

I have opened a PR (#14) that adds a `license` file to be consulted in the future, thanks a lot!
