### ISSUE TITLE
Base.scss file not found

### ISSUE THREAD

**Issue by arrontp** [csalmeida/hozokit#22]
**Setup:**  Using Hozokit Generator.

On `npm run start` the following error occurs at _`styles`_.

```
Error: File not found with singular glob
**AT**
/styles/base.scss

(if this was purposeful, use `allowEmpty` option)
```

Gulp is looking for this file but doesn't exist from generator. 

> Note: this is on main and not v2.0.0

**Comment by csalmeida** [comment]
Thanks for testing this Arron, so essentially you've ran:

- `yo hozokit`
- `cd hozokit-site`
- `npm install`
- `npm run start`

It does look like the generator template does need updating before it can be used but it shouldn't be empty: https://github.com/csalmeida/generator-hozokit/blob/main/generators/app/templates/theme/base.scss

Will look into it 🙏

**Comment by csalmeida** [comment]
Project will be archived soon, closing.
